[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-musl-cross/bin/mipsel-linux-musl-gcc"
rustflags = ["-Ctarget-feature=+crt-static"]

# [unstable]
# build-std = ["std","core","alloc","panic_abort"]
# build-std-features = ["panic_immediate_abort"]
