[target.'cfg(all(target_env = "musl"))']
rustflags = ["-Ctarget-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-musleabi-cross/bin/arm-linux-musleabi-gcc"

[target.i686-unknown-linux-musl]
linker = "i686-linux-musl-cross/bin/i686-linux-musl-gcc"

[target.mips-unknown-linux-musl]
linker = "mips-linux-musl-cross/bin/mips-linux-musl-gcc"

[target.mips64-unknown-linux-muslabi64]
linker = "mips64-linux-musl-cross/bin/mips64-linux-musl-gcc"

[target.mips64el-unknown-linux-muslabi64]
linker = "mips64el-linux-musl-cross/bin/mips64el-linux-musl-gcc"

[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-musl-cross/bin/mipsel-linux-musl-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc"
